url: 'https://f1r3fly-io.github.io'
#baseurl: '/f1r3fly-io'
baseurl: ''
logo: f1r3fly-io-logo-bg.jpg

# Site settings
title: Concurrency for the People
company: F1R3FLY.io
email: ceo@f1r3fly.io
description: "F1R3FLY.io provides high throughput transaction servers and networks for Web3 and AI projects."


# Team names, titles and social links
people:
- name: Lucius Gregory Meredith
  pic: 1
  position: President and CEO
  social:
    - title: twitter
      url: f1r3flyceo
    - title: facebook
      url: https://www.facebook.com/leithaus
    - title: linkedin
      url: https://www.linkedin.com/in/lucius-meredith-547645/

- name: Ralph Benko
  pic: 2
  position: General Counsel
  social:
    - title: twitter
      url: thewebster
    - title: facebook
      url: https://www.facebook.com/thegoldstandard
    - title: linkedin
      url: https://www.linkedin.com/in/ralph-benko-60052/

- name: Jeff Turner
  pic: 3
  position: Product Manager
  social:
    - title: twitter
      url: https://twitter.com/composedao
    - title: facebook
      url: https://www.facebook.com/profile.php?id=100093193697201
    - title: linkedin
      url: https://www.linkedin.com/in/composedao/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/f1r3flyceo
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100093193697201
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: https://github.com/F1R3FLY-io

# Postal address (add as many lines as necessary)
address:
  - line: 9336 California Ave SW
  - line: Seattle, WA 98136

# Build settings
markdown: kramdown
permalink: pretty