url: 'https://f1r3fly-io.github.io'
baseurl: '/f1r3fly-io'

# Site settings
title: Concurrency for the People
email: ceo@f1r3fly.io
description: "F1R3FLY.io provides high throughput transaction servers and networks for Web3 and AI projects."


# Team names, titles and social links
people:
- name: Lucius Gregory Meredith
  pic: 1
  position: President and CEO
  social:
    - title: twitter
      url: f1r3flyceo
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Ralph Benko
  pic: 2
  position: General Counsel
  social:
    - title: twitter
      url: thewebster
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Jeff Turner
  pic: 3
  position: Product Manager
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/f1r3flyceo
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100093193697201
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: https://github.com/F1R3FLY-io

# Postal address (add as many lines as necessary)
address:
  - line: 9336 California Ave SW
  - line: Seattle, WA 98136

# Build settings
markdown: kramdown
permalink: pretty